name: Create and Save Milestone on Push

on:
  push:
    branches:
      - master

jobs:
  create_and_save_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create or Update Milestone
        id: milestone
        uses: peter-evans/create-or-update-milestone@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: Milestone for check
          due-on: ${{ github.event.head_commit.timestamp }}

      - name: Save Milestone
        if: ${{ success() }}
        run: echo "${{ steps.milestone.outputs.number }}|${{ steps.milestone.outputs.title }}|${{ steps.milestone.outputs.due_on }}" >> milestones.txt

      - name: Display All Milestones
        run: cat milestones.txt


