name: Create Milestone on Push

on:
  push:
    branches:
      - main

env:
  MILESTONE_TITLE: Milestone for check

jobs:
  create_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Milestone
        id: milestone
        uses: peter-evans/create-or-update-milestone@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.MILESTONE_TITLE }}
          due_date: ${{ steps.date.outputs.date }}

      - name: Get Milestones
        id: milestones
        run: echo "::set-output name=milestones::$(jq -c '.[] | {title: .title, due_date: .due_on}' milestones.json | jq -s)"

      - name: Display Milestones
        run: echo "${{ steps.milestones.outputs.milestones }}"
